; General binary integer comparator.
; Input: x#y where x and y are binary integers.
; Behavior: halt iff x < y, loop forever otherwise.
; Leading zeros are ignored during the internal comparison.
name: compare_binary
init: I
final: F
blank: _
tapes: 3
CMP_LEN _,0,0 -> CMP_LEN _,0,0 S,R,R
CMP_LEN _,0,1 -> CMP_LEN _,0,1 S,R,R
CMP_LEN _,0,_ -> LOOP _,0,_ S,S,S
CMP_LEN _,1,0 -> CMP_LEN _,1,0 S,R,R
CMP_LEN _,1,1 -> CMP_LEN _,1,1 S,R,R
CMP_LEN _,1,_ -> LOOP _,1,_ S,S,S
CMP_LEN _,_,0 -> F _,_,0 S,S,S
CMP_LEN _,_,1 -> F _,_,1 S,S,S
CMP_LEN _,_,_ -> REWIND_X2_PRE _,_,_ S,S,S
CMP_LEX _,0,0 -> CMP_LEX _,0,0 S,R,R
CMP_LEX _,0,1 -> F _,0,1 S,S,S
CMP_LEX _,1,0 -> LOOP _,1,0 S,S,S
CMP_LEX _,1,1 -> CMP_LEX _,1,1 S,R,R
CMP_LEX _,_,_ -> LOOP _,_,_ S,S,S
COPY_X #,_,_ -> COPY_Y_SKIP #,_,_ R,S,S
COPY_X 0,_,_ -> COPY_X 0,0,_ R,R,S
COPY_X 1,_,_ -> COPY_X 1,1,_ R,R,S
COPY_Y 0,#,_ -> COPY_Y 0,#,0 R,S,R
COPY_Y 0,0,_ -> COPY_Y 0,0,0 R,S,R
COPY_Y 0,1,_ -> COPY_Y 0,1,0 R,S,R
COPY_Y 0,_,_ -> COPY_Y 0,_,0 R,S,R
COPY_Y 0,|,_ -> COPY_Y 0,|,0 R,S,R
COPY_Y 1,#,_ -> COPY_Y 1,#,1 R,S,R
COPY_Y 1,0,_ -> COPY_Y 1,0,1 R,S,R
COPY_Y 1,1,_ -> COPY_Y 1,1,1 R,S,R
COPY_Y 1,_,_ -> COPY_Y 1,_,1 R,S,R
COPY_Y 1,|,_ -> COPY_Y 1,|,1 R,S,R
COPY_Y _,#,_ -> REWIND_X_PRE _,#,_ S,S,S
COPY_Y _,0,_ -> REWIND_X_PRE _,0,_ S,S,S
COPY_Y _,1,_ -> REWIND_X_PRE _,1,_ S,S,S
COPY_Y _,_,_ -> REWIND_X_PRE _,_,_ S,S,S
COPY_Y _,|,_ -> REWIND_X_PRE _,|,_ S,S,S
COPY_Y_SKIP 0,#,_ -> COPY_Y_SKIP 0,#,_ R,S,S
COPY_Y_SKIP 0,0,_ -> COPY_Y_SKIP 0,0,_ R,S,S
COPY_Y_SKIP 0,1,_ -> COPY_Y_SKIP 0,1,_ R,S,S
COPY_Y_SKIP 0,_,_ -> COPY_Y_SKIP 0,_,_ R,S,S
COPY_Y_SKIP 0,|,_ -> COPY_Y_SKIP 0,|,_ R,S,S
COPY_Y_SKIP 1,#,_ -> COPY_Y 1,#,1 R,S,R
COPY_Y_SKIP 1,0,_ -> COPY_Y 1,0,1 R,S,R
COPY_Y_SKIP 1,1,_ -> COPY_Y 1,1,1 R,S,R
COPY_Y_SKIP 1,_,_ -> COPY_Y 1,_,1 R,S,R
COPY_Y_SKIP 1,|,_ -> COPY_Y 1,|,1 R,S,R
COPY_Y_SKIP _,#,_ -> REWIND_X_PRE _,#,0 S,S,R
COPY_Y_SKIP _,0,_ -> REWIND_X_PRE _,0,0 S,S,R
COPY_Y_SKIP _,1,_ -> REWIND_X_PRE _,1,0 S,S,R
COPY_Y_SKIP _,_,_ -> REWIND_X_PRE _,_,0 S,S,R
COPY_Y_SKIP _,|,_ -> REWIND_X_PRE _,|,0 S,S,R
I #,_,_ -> COPY_Y_SKIP #,0,_ R,R,S
I 0,_,_ -> I 0,_,_ R,S,S
I 1,_,_ -> COPY_X 1,1,_ R,R,S
LOOP #,#,# -> LOOP #,#,# S,S,S
LOOP #,#,0 -> LOOP #,#,0 S,S,S
LOOP #,#,1 -> LOOP #,#,1 S,S,S
LOOP #,#,_ -> LOOP #,#,_ S,S,S
LOOP #,#,| -> LOOP #,#,| S,S,S
LOOP #,0,# -> LOOP #,0,# S,S,S
LOOP #,0,0 -> LOOP #,0,0 S,S,S
LOOP #,0,1 -> LOOP #,0,1 S,S,S
LOOP #,0,_ -> LOOP #,0,_ S,S,S
LOOP #,0,| -> LOOP #,0,| S,S,S
LOOP #,1,# -> LOOP #,1,# S,S,S
LOOP #,1,0 -> LOOP #,1,0 S,S,S
LOOP #,1,1 -> LOOP #,1,1 S,S,S
LOOP #,1,_ -> LOOP #,1,_ S,S,S
LOOP #,1,| -> LOOP #,1,| S,S,S
LOOP #,_,# -> LOOP #,_,# S,S,S
LOOP #,_,0 -> LOOP #,_,0 S,S,S
LOOP #,_,1 -> LOOP #,_,1 S,S,S
LOOP #,_,_ -> LOOP #,_,_ S,S,S
LOOP #,_,| -> LOOP #,_,| S,S,S
LOOP #,|,# -> LOOP #,|,# S,S,S
LOOP #,|,0 -> LOOP #,|,0 S,S,S
LOOP #,|,1 -> LOOP #,|,1 S,S,S
LOOP #,|,_ -> LOOP #,|,_ S,S,S
LOOP #,|,| -> LOOP #,|,| S,S,S
LOOP 0,#,# -> LOOP 0,#,# S,S,S
LOOP 0,#,0 -> LOOP 0,#,0 S,S,S
LOOP 0,#,1 -> LOOP 0,#,1 S,S,S
LOOP 0,#,_ -> LOOP 0,#,_ S,S,S
LOOP 0,#,| -> LOOP 0,#,| S,S,S
LOOP 0,0,# -> LOOP 0,0,# S,S,S
LOOP 0,0,0 -> LOOP 0,0,0 S,S,S
LOOP 0,0,1 -> LOOP 0,0,1 S,S,S
LOOP 0,0,_ -> LOOP 0,0,_ S,S,S
LOOP 0,0,| -> LOOP 0,0,| S,S,S
LOOP 0,1,# -> LOOP 0,1,# S,S,S
LOOP 0,1,0 -> LOOP 0,1,0 S,S,S
LOOP 0,1,1 -> LOOP 0,1,1 S,S,S
LOOP 0,1,_ -> LOOP 0,1,_ S,S,S
LOOP 0,1,| -> LOOP 0,1,| S,S,S
LOOP 0,_,# -> LOOP 0,_,# S,S,S
LOOP 0,_,0 -> LOOP 0,_,0 S,S,S
LOOP 0,_,1 -> LOOP 0,_,1 S,S,S
LOOP 0,_,_ -> LOOP 0,_,_ S,S,S
LOOP 0,_,| -> LOOP 0,_,| S,S,S
LOOP 0,|,# -> LOOP 0,|,# S,S,S
LOOP 0,|,0 -> LOOP 0,|,0 S,S,S
LOOP 0,|,1 -> LOOP 0,|,1 S,S,S
LOOP 0,|,_ -> LOOP 0,|,_ S,S,S
LOOP 0,|,| -> LOOP 0,|,| S,S,S
LOOP 1,#,# -> LOOP 1,#,# S,S,S
LOOP 1,#,0 -> LOOP 1,#,0 S,S,S
LOOP 1,#,1 -> LOOP 1,#,1 S,S,S
LOOP 1,#,_ -> LOOP 1,#,_ S,S,S
LOOP 1,#,| -> LOOP 1,#,| S,S,S
LOOP 1,0,# -> LOOP 1,0,# S,S,S
LOOP 1,0,0 -> LOOP 1,0,0 S,S,S
LOOP 1,0,1 -> LOOP 1,0,1 S,S,S
LOOP 1,0,_ -> LOOP 1,0,_ S,S,S
LOOP 1,0,| -> LOOP 1,0,| S,S,S
LOOP 1,1,# -> LOOP 1,1,# S,S,S
LOOP 1,1,0 -> LOOP 1,1,0 S,S,S
LOOP 1,1,1 -> LOOP 1,1,1 S,S,S
LOOP 1,1,_ -> LOOP 1,1,_ S,S,S
LOOP 1,1,| -> LOOP 1,1,| S,S,S
LOOP 1,_,# -> LOOP 1,_,# S,S,S
LOOP 1,_,0 -> LOOP 1,_,0 S,S,S
LOOP 1,_,1 -> LOOP 1,_,1 S,S,S
LOOP 1,_,_ -> LOOP 1,_,_ S,S,S
LOOP 1,_,| -> LOOP 1,_,| S,S,S
LOOP 1,|,# -> LOOP 1,|,# S,S,S
LOOP 1,|,0 -> LOOP 1,|,0 S,S,S
LOOP 1,|,1 -> LOOP 1,|,1 S,S,S
LOOP 1,|,_ -> LOOP 1,|,_ S,S,S
LOOP 1,|,| -> LOOP 1,|,| S,S,S
LOOP _,#,# -> LOOP _,#,# S,S,S
LOOP _,#,0 -> LOOP _,#,0 S,S,S
LOOP _,#,1 -> LOOP _,#,1 S,S,S
LOOP _,#,_ -> LOOP _,#,_ S,S,S
LOOP _,#,| -> LOOP _,#,| S,S,S
LOOP _,0,# -> LOOP _,0,# S,S,S
LOOP _,0,0 -> LOOP _,0,0 S,S,S
LOOP _,0,1 -> LOOP _,0,1 S,S,S
LOOP _,0,_ -> LOOP _,0,_ S,S,S
LOOP _,0,| -> LOOP _,0,| S,S,S
LOOP _,1,# -> LOOP _,1,# S,S,S
LOOP _,1,0 -> LOOP _,1,0 S,S,S
LOOP _,1,1 -> LOOP _,1,1 S,S,S
LOOP _,1,_ -> LOOP _,1,_ S,S,S
LOOP _,1,| -> LOOP _,1,| S,S,S
LOOP _,_,# -> LOOP _,_,# S,S,S
LOOP _,_,0 -> LOOP _,_,0 S,S,S
LOOP _,_,1 -> LOOP _,_,1 S,S,S
LOOP _,_,_ -> LOOP _,_,_ S,S,S
LOOP _,_,| -> LOOP _,_,| S,S,S
LOOP _,|,# -> LOOP _,|,# S,S,S
LOOP _,|,0 -> LOOP _,|,0 S,S,S
LOOP _,|,1 -> LOOP _,|,1 S,S,S
LOOP _,|,_ -> LOOP _,|,_ S,S,S
LOOP _,|,| -> LOOP _,|,| S,S,S
LOOP |,#,# -> LOOP |,#,# S,S,S
LOOP |,#,0 -> LOOP |,#,0 S,S,S
LOOP |,#,1 -> LOOP |,#,1 S,S,S
LOOP |,#,_ -> LOOP |,#,_ S,S,S
LOOP |,#,| -> LOOP |,#,| S,S,S
LOOP |,0,# -> LOOP |,0,# S,S,S
LOOP |,0,0 -> LOOP |,0,0 S,S,S
LOOP |,0,1 -> LOOP |,0,1 S,S,S
LOOP |,0,_ -> LOOP |,0,_ S,S,S
LOOP |,0,| -> LOOP |,0,| S,S,S
LOOP |,1,# -> LOOP |,1,# S,S,S
LOOP |,1,0 -> LOOP |,1,0 S,S,S
LOOP |,1,1 -> LOOP |,1,1 S,S,S
LOOP |,1,_ -> LOOP |,1,_ S,S,S
LOOP |,1,| -> LOOP |,1,| S,S,S
LOOP |,_,# -> LOOP |,_,# S,S,S
LOOP |,_,0 -> LOOP |,_,0 S,S,S
LOOP |,_,1 -> LOOP |,_,1 S,S,S
LOOP |,_,_ -> LOOP |,_,_ S,S,S
LOOP |,_,| -> LOOP |,_,| S,S,S
LOOP |,|,# -> LOOP |,|,# S,S,S
LOOP |,|,0 -> LOOP |,|,0 S,S,S
LOOP |,|,1 -> LOOP |,|,1 S,S,S
LOOP |,|,_ -> LOOP |,|,_ S,S,S
LOOP |,|,| -> LOOP |,|,| S,S,S
REWIND_X #,0,# -> REWIND_X #,0,# S,L,S
REWIND_X #,0,0 -> REWIND_X #,0,0 S,L,S
REWIND_X #,0,1 -> REWIND_X #,0,1 S,L,S
REWIND_X #,0,_ -> REWIND_X #,0,_ S,L,S
REWIND_X #,0,| -> REWIND_X #,0,| S,L,S
REWIND_X #,1,# -> REWIND_X #,1,# S,L,S
REWIND_X #,1,0 -> REWIND_X #,1,0 S,L,S
REWIND_X #,1,1 -> REWIND_X #,1,1 S,L,S
REWIND_X #,1,_ -> REWIND_X #,1,_ S,L,S
REWIND_X #,1,| -> REWIND_X #,1,| S,L,S
REWIND_X #,_,# -> REWIND_Y_PRE #,_,# S,R,S
REWIND_X #,_,0 -> REWIND_Y_PRE #,_,0 S,R,S
REWIND_X #,_,1 -> REWIND_Y_PRE #,_,1 S,R,S
REWIND_X #,_,_ -> REWIND_Y_PRE #,_,_ S,R,S
REWIND_X #,_,| -> REWIND_Y_PRE #,_,| S,R,S
REWIND_X 0,0,# -> REWIND_X 0,0,# S,L,S
REWIND_X 0,0,0 -> REWIND_X 0,0,0 S,L,S
REWIND_X 0,0,1 -> REWIND_X 0,0,1 S,L,S
REWIND_X 0,0,_ -> REWIND_X 0,0,_ S,L,S
REWIND_X 0,0,| -> REWIND_X 0,0,| S,L,S
REWIND_X 0,1,# -> REWIND_X 0,1,# S,L,S
REWIND_X 0,1,0 -> REWIND_X 0,1,0 S,L,S
REWIND_X 0,1,1 -> REWIND_X 0,1,1 S,L,S
REWIND_X 0,1,_ -> REWIND_X 0,1,_ S,L,S
REWIND_X 0,1,| -> REWIND_X 0,1,| S,L,S
REWIND_X 0,_,# -> REWIND_Y_PRE 0,_,# S,R,S
REWIND_X 0,_,0 -> REWIND_Y_PRE 0,_,0 S,R,S
REWIND_X 0,_,1 -> REWIND_Y_PRE 0,_,1 S,R,S
REWIND_X 0,_,_ -> REWIND_Y_PRE 0,_,_ S,R,S
REWIND_X 0,_,| -> REWIND_Y_PRE 0,_,| S,R,S
REWIND_X 1,0,# -> REWIND_X 1,0,# S,L,S
REWIND_X 1,0,0 -> REWIND_X 1,0,0 S,L,S
REWIND_X 1,0,1 -> REWIND_X 1,0,1 S,L,S
REWIND_X 1,0,_ -> REWIND_X 1,0,_ S,L,S
REWIND_X 1,0,| -> REWIND_X 1,0,| S,L,S
REWIND_X 1,1,# -> REWIND_X 1,1,# S,L,S
REWIND_X 1,1,0 -> REWIND_X 1,1,0 S,L,S
REWIND_X 1,1,1 -> REWIND_X 1,1,1 S,L,S
REWIND_X 1,1,_ -> REWIND_X 1,1,_ S,L,S
REWIND_X 1,1,| -> REWIND_X 1,1,| S,L,S
REWIND_X 1,_,# -> REWIND_Y_PRE 1,_,# S,R,S
REWIND_X 1,_,0 -> REWIND_Y_PRE 1,_,0 S,R,S
REWIND_X 1,_,1 -> REWIND_Y_PRE 1,_,1 S,R,S
REWIND_X 1,_,_ -> REWIND_Y_PRE 1,_,_ S,R,S
REWIND_X 1,_,| -> REWIND_Y_PRE 1,_,| S,R,S
REWIND_X _,0,# -> REWIND_X _,0,# S,L,S
REWIND_X _,0,0 -> REWIND_X _,0,0 S,L,S
REWIND_X _,0,1 -> REWIND_X _,0,1 S,L,S
REWIND_X _,0,_ -> REWIND_X _,0,_ S,L,S
REWIND_X _,0,| -> REWIND_X _,0,| S,L,S
REWIND_X _,1,# -> REWIND_X _,1,# S,L,S
REWIND_X _,1,0 -> REWIND_X _,1,0 S,L,S
REWIND_X _,1,1 -> REWIND_X _,1,1 S,L,S
REWIND_X _,1,_ -> REWIND_X _,1,_ S,L,S
REWIND_X _,1,| -> REWIND_X _,1,| S,L,S
REWIND_X _,_,# -> REWIND_Y_PRE _,_,# S,R,S
REWIND_X _,_,0 -> REWIND_Y_PRE _,_,0 S,R,S
REWIND_X _,_,1 -> REWIND_Y_PRE _,_,1 S,R,S
REWIND_X _,_,_ -> REWIND_Y_PRE _,_,_ S,R,S
REWIND_X _,_,| -> REWIND_Y_PRE _,_,| S,R,S
REWIND_X |,0,# -> REWIND_X |,0,# S,L,S
REWIND_X |,0,0 -> REWIND_X |,0,0 S,L,S
REWIND_X |,0,1 -> REWIND_X |,0,1 S,L,S
REWIND_X |,0,_ -> REWIND_X |,0,_ S,L,S
REWIND_X |,0,| -> REWIND_X |,0,| S,L,S
REWIND_X |,1,# -> REWIND_X |,1,# S,L,S
REWIND_X |,1,0 -> REWIND_X |,1,0 S,L,S
REWIND_X |,1,1 -> REWIND_X |,1,1 S,L,S
REWIND_X |,1,_ -> REWIND_X |,1,_ S,L,S
REWIND_X |,1,| -> REWIND_X |,1,| S,L,S
REWIND_X |,_,# -> REWIND_Y_PRE |,_,# S,R,S
REWIND_X |,_,0 -> REWIND_Y_PRE |,_,0 S,R,S
REWIND_X |,_,1 -> REWIND_Y_PRE |,_,1 S,R,S
REWIND_X |,_,_ -> REWIND_Y_PRE |,_,_ S,R,S
REWIND_X |,_,| -> REWIND_Y_PRE |,_,| S,R,S
REWIND_X2 #,0,# -> REWIND_X2 #,0,# S,L,S
REWIND_X2 #,0,0 -> REWIND_X2 #,0,0 S,L,S
REWIND_X2 #,0,1 -> REWIND_X2 #,0,1 S,L,S
REWIND_X2 #,0,_ -> REWIND_X2 #,0,_ S,L,S
REWIND_X2 #,0,| -> REWIND_X2 #,0,| S,L,S
REWIND_X2 #,1,# -> REWIND_X2 #,1,# S,L,S
REWIND_X2 #,1,0 -> REWIND_X2 #,1,0 S,L,S
REWIND_X2 #,1,1 -> REWIND_X2 #,1,1 S,L,S
REWIND_X2 #,1,_ -> REWIND_X2 #,1,_ S,L,S
REWIND_X2 #,1,| -> REWIND_X2 #,1,| S,L,S
REWIND_X2 #,_,# -> REWIND_Y2_PRE #,_,# S,R,S
REWIND_X2 #,_,0 -> REWIND_Y2_PRE #,_,0 S,R,S
REWIND_X2 #,_,1 -> REWIND_Y2_PRE #,_,1 S,R,S
REWIND_X2 #,_,_ -> REWIND_Y2_PRE #,_,_ S,R,S
REWIND_X2 #,_,| -> REWIND_Y2_PRE #,_,| S,R,S
REWIND_X2 0,0,# -> REWIND_X2 0,0,# S,L,S
REWIND_X2 0,0,0 -> REWIND_X2 0,0,0 S,L,S
REWIND_X2 0,0,1 -> REWIND_X2 0,0,1 S,L,S
REWIND_X2 0,0,_ -> REWIND_X2 0,0,_ S,L,S
REWIND_X2 0,0,| -> REWIND_X2 0,0,| S,L,S
REWIND_X2 0,1,# -> REWIND_X2 0,1,# S,L,S
REWIND_X2 0,1,0 -> REWIND_X2 0,1,0 S,L,S
REWIND_X2 0,1,1 -> REWIND_X2 0,1,1 S,L,S
REWIND_X2 0,1,_ -> REWIND_X2 0,1,_ S,L,S
REWIND_X2 0,1,| -> REWIND_X2 0,1,| S,L,S
REWIND_X2 0,_,# -> REWIND_Y2_PRE 0,_,# S,R,S
REWIND_X2 0,_,0 -> REWIND_Y2_PRE 0,_,0 S,R,S
REWIND_X2 0,_,1 -> REWIND_Y2_PRE 0,_,1 S,R,S
REWIND_X2 0,_,_ -> REWIND_Y2_PRE 0,_,_ S,R,S
REWIND_X2 0,_,| -> REWIND_Y2_PRE 0,_,| S,R,S
REWIND_X2 1,0,# -> REWIND_X2 1,0,# S,L,S
REWIND_X2 1,0,0 -> REWIND_X2 1,0,0 S,L,S
REWIND_X2 1,0,1 -> REWIND_X2 1,0,1 S,L,S
REWIND_X2 1,0,_ -> REWIND_X2 1,0,_ S,L,S
REWIND_X2 1,0,| -> REWIND_X2 1,0,| S,L,S
REWIND_X2 1,1,# -> REWIND_X2 1,1,# S,L,S
REWIND_X2 1,1,0 -> REWIND_X2 1,1,0 S,L,S
REWIND_X2 1,1,1 -> REWIND_X2 1,1,1 S,L,S
REWIND_X2 1,1,_ -> REWIND_X2 1,1,_ S,L,S
REWIND_X2 1,1,| -> REWIND_X2 1,1,| S,L,S
REWIND_X2 1,_,# -> REWIND_Y2_PRE 1,_,# S,R,S
REWIND_X2 1,_,0 -> REWIND_Y2_PRE 1,_,0 S,R,S
REWIND_X2 1,_,1 -> REWIND_Y2_PRE 1,_,1 S,R,S
REWIND_X2 1,_,_ -> REWIND_Y2_PRE 1,_,_ S,R,S
REWIND_X2 1,_,| -> REWIND_Y2_PRE 1,_,| S,R,S
REWIND_X2 _,0,# -> REWIND_X2 _,0,# S,L,S
REWIND_X2 _,0,0 -> REWIND_X2 _,0,0 S,L,S
REWIND_X2 _,0,1 -> REWIND_X2 _,0,1 S,L,S
REWIND_X2 _,0,_ -> REWIND_X2 _,0,_ S,L,S
REWIND_X2 _,0,| -> REWIND_X2 _,0,| S,L,S
REWIND_X2 _,1,# -> REWIND_X2 _,1,# S,L,S
REWIND_X2 _,1,0 -> REWIND_X2 _,1,0 S,L,S
REWIND_X2 _,1,1 -> REWIND_X2 _,1,1 S,L,S
REWIND_X2 _,1,_ -> REWIND_X2 _,1,_ S,L,S
REWIND_X2 _,1,| -> REWIND_X2 _,1,| S,L,S
REWIND_X2 _,_,# -> REWIND_Y2_PRE _,_,# S,R,S
REWIND_X2 _,_,0 -> REWIND_Y2_PRE _,_,0 S,R,S
REWIND_X2 _,_,1 -> REWIND_Y2_PRE _,_,1 S,R,S
REWIND_X2 _,_,_ -> REWIND_Y2_PRE _,_,_ S,R,S
REWIND_X2 _,_,| -> REWIND_Y2_PRE _,_,| S,R,S
REWIND_X2 |,0,# -> REWIND_X2 |,0,# S,L,S
REWIND_X2 |,0,0 -> REWIND_X2 |,0,0 S,L,S
REWIND_X2 |,0,1 -> REWIND_X2 |,0,1 S,L,S
REWIND_X2 |,0,_ -> REWIND_X2 |,0,_ S,L,S
REWIND_X2 |,0,| -> REWIND_X2 |,0,| S,L,S
REWIND_X2 |,1,# -> REWIND_X2 |,1,# S,L,S
REWIND_X2 |,1,0 -> REWIND_X2 |,1,0 S,L,S
REWIND_X2 |,1,1 -> REWIND_X2 |,1,1 S,L,S
REWIND_X2 |,1,_ -> REWIND_X2 |,1,_ S,L,S
REWIND_X2 |,1,| -> REWIND_X2 |,1,| S,L,S
REWIND_X2 |,_,# -> REWIND_Y2_PRE |,_,# S,R,S
REWIND_X2 |,_,0 -> REWIND_Y2_PRE |,_,0 S,R,S
REWIND_X2 |,_,1 -> REWIND_Y2_PRE |,_,1 S,R,S
REWIND_X2 |,_,_ -> REWIND_Y2_PRE |,_,_ S,R,S
REWIND_X2 |,_,| -> REWIND_Y2_PRE |,_,| S,R,S
REWIND_X2_PRE #,_,# -> REWIND_X2 #,_,# S,L,S
REWIND_X2_PRE #,_,0 -> REWIND_X2 #,_,0 S,L,S
REWIND_X2_PRE #,_,1 -> REWIND_X2 #,_,1 S,L,S
REWIND_X2_PRE #,_,_ -> REWIND_X2 #,_,_ S,L,S
REWIND_X2_PRE #,_,| -> REWIND_X2 #,_,| S,L,S
REWIND_X2_PRE 0,_,# -> REWIND_X2 0,_,# S,L,S
REWIND_X2_PRE 0,_,0 -> REWIND_X2 0,_,0 S,L,S
REWIND_X2_PRE 0,_,1 -> REWIND_X2 0,_,1 S,L,S
REWIND_X2_PRE 0,_,_ -> REWIND_X2 0,_,_ S,L,S
REWIND_X2_PRE 0,_,| -> REWIND_X2 0,_,| S,L,S
REWIND_X2_PRE 1,_,# -> REWIND_X2 1,_,# S,L,S
REWIND_X2_PRE 1,_,0 -> REWIND_X2 1,_,0 S,L,S
REWIND_X2_PRE 1,_,1 -> REWIND_X2 1,_,1 S,L,S
REWIND_X2_PRE 1,_,_ -> REWIND_X2 1,_,_ S,L,S
REWIND_X2_PRE 1,_,| -> REWIND_X2 1,_,| S,L,S
REWIND_X2_PRE _,_,# -> REWIND_X2 _,_,# S,L,S
REWIND_X2_PRE _,_,0 -> REWIND_X2 _,_,0 S,L,S
REWIND_X2_PRE _,_,1 -> REWIND_X2 _,_,1 S,L,S
REWIND_X2_PRE _,_,_ -> REWIND_X2 _,_,_ S,L,S
REWIND_X2_PRE _,_,| -> REWIND_X2 _,_,| S,L,S
REWIND_X2_PRE |,_,# -> REWIND_X2 |,_,# S,L,S
REWIND_X2_PRE |,_,0 -> REWIND_X2 |,_,0 S,L,S
REWIND_X2_PRE |,_,1 -> REWIND_X2 |,_,1 S,L,S
REWIND_X2_PRE |,_,_ -> REWIND_X2 |,_,_ S,L,S
REWIND_X2_PRE |,_,| -> REWIND_X2 |,_,| S,L,S
REWIND_X_PRE #,_,# -> REWIND_X #,_,# S,L,S
REWIND_X_PRE #,_,0 -> REWIND_X #,_,0 S,L,S
REWIND_X_PRE #,_,1 -> REWIND_X #,_,1 S,L,S
REWIND_X_PRE #,_,_ -> REWIND_X #,_,_ S,L,S
REWIND_X_PRE #,_,| -> REWIND_X #,_,| S,L,S
REWIND_X_PRE 0,_,# -> REWIND_X 0,_,# S,L,S
REWIND_X_PRE 0,_,0 -> REWIND_X 0,_,0 S,L,S
REWIND_X_PRE 0,_,1 -> REWIND_X 0,_,1 S,L,S
REWIND_X_PRE 0,_,_ -> REWIND_X 0,_,_ S,L,S
REWIND_X_PRE 0,_,| -> REWIND_X 0,_,| S,L,S
REWIND_X_PRE 1,_,# -> REWIND_X 1,_,# S,L,S
REWIND_X_PRE 1,_,0 -> REWIND_X 1,_,0 S,L,S
REWIND_X_PRE 1,_,1 -> REWIND_X 1,_,1 S,L,S
REWIND_X_PRE 1,_,_ -> REWIND_X 1,_,_ S,L,S
REWIND_X_PRE 1,_,| -> REWIND_X 1,_,| S,L,S
REWIND_X_PRE _,_,# -> REWIND_X _,_,# S,L,S
REWIND_X_PRE _,_,0 -> REWIND_X _,_,0 S,L,S
REWIND_X_PRE _,_,1 -> REWIND_X _,_,1 S,L,S
REWIND_X_PRE _,_,_ -> REWIND_X _,_,_ S,L,S
REWIND_X_PRE _,_,| -> REWIND_X _,_,| S,L,S
REWIND_X_PRE |,_,# -> REWIND_X |,_,# S,L,S
REWIND_X_PRE |,_,0 -> REWIND_X |,_,0 S,L,S
REWIND_X_PRE |,_,1 -> REWIND_X |,_,1 S,L,S
REWIND_X_PRE |,_,_ -> REWIND_X |,_,_ S,L,S
REWIND_X_PRE |,_,| -> REWIND_X |,_,| S,L,S
REWIND_Y #,#,0 -> REWIND_Y #,#,0 S,S,L
REWIND_Y #,#,1 -> REWIND_Y #,#,1 S,S,L
REWIND_Y #,#,_ -> CMP_LEN #,#,_ S,S,R
REWIND_Y #,0,0 -> REWIND_Y #,0,0 S,S,L
REWIND_Y #,0,1 -> REWIND_Y #,0,1 S,S,L
REWIND_Y #,0,_ -> CMP_LEN #,0,_ S,S,R
REWIND_Y #,1,0 -> REWIND_Y #,1,0 S,S,L
REWIND_Y #,1,1 -> REWIND_Y #,1,1 S,S,L
REWIND_Y #,1,_ -> CMP_LEN #,1,_ S,S,R
REWIND_Y #,_,0 -> REWIND_Y #,_,0 S,S,L
REWIND_Y #,_,1 -> REWIND_Y #,_,1 S,S,L
REWIND_Y #,_,_ -> CMP_LEN #,_,_ S,S,R
REWIND_Y #,|,0 -> REWIND_Y #,|,0 S,S,L
REWIND_Y #,|,1 -> REWIND_Y #,|,1 S,S,L
REWIND_Y #,|,_ -> CMP_LEN #,|,_ S,S,R
REWIND_Y 0,#,0 -> REWIND_Y 0,#,0 S,S,L
REWIND_Y 0,#,1 -> REWIND_Y 0,#,1 S,S,L
REWIND_Y 0,#,_ -> CMP_LEN 0,#,_ S,S,R
REWIND_Y 0,0,0 -> REWIND_Y 0,0,0 S,S,L
REWIND_Y 0,0,1 -> REWIND_Y 0,0,1 S,S,L
REWIND_Y 0,0,_ -> CMP_LEN 0,0,_ S,S,R
REWIND_Y 0,1,0 -> REWIND_Y 0,1,0 S,S,L
REWIND_Y 0,1,1 -> REWIND_Y 0,1,1 S,S,L
REWIND_Y 0,1,_ -> CMP_LEN 0,1,_ S,S,R
REWIND_Y 0,_,0 -> REWIND_Y 0,_,0 S,S,L
REWIND_Y 0,_,1 -> REWIND_Y 0,_,1 S,S,L
REWIND_Y 0,_,_ -> CMP_LEN 0,_,_ S,S,R
REWIND_Y 0,|,0 -> REWIND_Y 0,|,0 S,S,L
REWIND_Y 0,|,1 -> REWIND_Y 0,|,1 S,S,L
REWIND_Y 0,|,_ -> CMP_LEN 0,|,_ S,S,R
REWIND_Y 1,#,0 -> REWIND_Y 1,#,0 S,S,L
REWIND_Y 1,#,1 -> REWIND_Y 1,#,1 S,S,L
REWIND_Y 1,#,_ -> CMP_LEN 1,#,_ S,S,R
REWIND_Y 1,0,0 -> REWIND_Y 1,0,0 S,S,L
REWIND_Y 1,0,1 -> REWIND_Y 1,0,1 S,S,L
REWIND_Y 1,0,_ -> CMP_LEN 1,0,_ S,S,R
REWIND_Y 1,1,0 -> REWIND_Y 1,1,0 S,S,L
REWIND_Y 1,1,1 -> REWIND_Y 1,1,1 S,S,L
REWIND_Y 1,1,_ -> CMP_LEN 1,1,_ S,S,R
REWIND_Y 1,_,0 -> REWIND_Y 1,_,0 S,S,L
REWIND_Y 1,_,1 -> REWIND_Y 1,_,1 S,S,L
REWIND_Y 1,_,_ -> CMP_LEN 1,_,_ S,S,R
REWIND_Y 1,|,0 -> REWIND_Y 1,|,0 S,S,L
REWIND_Y 1,|,1 -> REWIND_Y 1,|,1 S,S,L
REWIND_Y 1,|,_ -> CMP_LEN 1,|,_ S,S,R
REWIND_Y _,#,0 -> REWIND_Y _,#,0 S,S,L
REWIND_Y _,#,1 -> REWIND_Y _,#,1 S,S,L
REWIND_Y _,#,_ -> CMP_LEN _,#,_ S,S,R
REWIND_Y _,0,0 -> REWIND_Y _,0,0 S,S,L
REWIND_Y _,0,1 -> REWIND_Y _,0,1 S,S,L
REWIND_Y _,0,_ -> CMP_LEN _,0,_ S,S,R
REWIND_Y _,1,0 -> REWIND_Y _,1,0 S,S,L
REWIND_Y _,1,1 -> REWIND_Y _,1,1 S,S,L
REWIND_Y _,1,_ -> CMP_LEN _,1,_ S,S,R
REWIND_Y _,_,0 -> REWIND_Y _,_,0 S,S,L
REWIND_Y _,_,1 -> REWIND_Y _,_,1 S,S,L
REWIND_Y _,_,_ -> CMP_LEN _,_,_ S,S,R
REWIND_Y _,|,0 -> REWIND_Y _,|,0 S,S,L
REWIND_Y _,|,1 -> REWIND_Y _,|,1 S,S,L
REWIND_Y _,|,_ -> CMP_LEN _,|,_ S,S,R
REWIND_Y |,#,0 -> REWIND_Y |,#,0 S,S,L
REWIND_Y |,#,1 -> REWIND_Y |,#,1 S,S,L
REWIND_Y |,#,_ -> CMP_LEN |,#,_ S,S,R
REWIND_Y |,0,0 -> REWIND_Y |,0,0 S,S,L
REWIND_Y |,0,1 -> REWIND_Y |,0,1 S,S,L
REWIND_Y |,0,_ -> CMP_LEN |,0,_ S,S,R
REWIND_Y |,1,0 -> REWIND_Y |,1,0 S,S,L
REWIND_Y |,1,1 -> REWIND_Y |,1,1 S,S,L
REWIND_Y |,1,_ -> CMP_LEN |,1,_ S,S,R
REWIND_Y |,_,0 -> REWIND_Y |,_,0 S,S,L
REWIND_Y |,_,1 -> REWIND_Y |,_,1 S,S,L
REWIND_Y |,_,_ -> CMP_LEN |,_,_ S,S,R
REWIND_Y |,|,0 -> REWIND_Y |,|,0 S,S,L
REWIND_Y |,|,1 -> REWIND_Y |,|,1 S,S,L
REWIND_Y |,|,_ -> CMP_LEN |,|,_ S,S,R
REWIND_Y2 #,#,0 -> REWIND_Y2 #,#,0 S,S,L
REWIND_Y2 #,#,1 -> REWIND_Y2 #,#,1 S,S,L
REWIND_Y2 #,#,_ -> CMP_LEX #,#,_ S,S,R
REWIND_Y2 #,0,0 -> REWIND_Y2 #,0,0 S,S,L
REWIND_Y2 #,0,1 -> REWIND_Y2 #,0,1 S,S,L
REWIND_Y2 #,0,_ -> CMP_LEX #,0,_ S,S,R
REWIND_Y2 #,1,0 -> REWIND_Y2 #,1,0 S,S,L
REWIND_Y2 #,1,1 -> REWIND_Y2 #,1,1 S,S,L
REWIND_Y2 #,1,_ -> CMP_LEX #,1,_ S,S,R
REWIND_Y2 #,_,0 -> REWIND_Y2 #,_,0 S,S,L
REWIND_Y2 #,_,1 -> REWIND_Y2 #,_,1 S,S,L
REWIND_Y2 #,_,_ -> CMP_LEX #,_,_ S,S,R
REWIND_Y2 #,|,0 -> REWIND_Y2 #,|,0 S,S,L
REWIND_Y2 #,|,1 -> REWIND_Y2 #,|,1 S,S,L
REWIND_Y2 #,|,_ -> CMP_LEX #,|,_ S,S,R
REWIND_Y2 0,#,0 -> REWIND_Y2 0,#,0 S,S,L
REWIND_Y2 0,#,1 -> REWIND_Y2 0,#,1 S,S,L
REWIND_Y2 0,#,_ -> CMP_LEX 0,#,_ S,S,R
REWIND_Y2 0,0,0 -> REWIND_Y2 0,0,0 S,S,L
REWIND_Y2 0,0,1 -> REWIND_Y2 0,0,1 S,S,L
REWIND_Y2 0,0,_ -> CMP_LEX 0,0,_ S,S,R
REWIND_Y2 0,1,0 -> REWIND_Y2 0,1,0 S,S,L
REWIND_Y2 0,1,1 -> REWIND_Y2 0,1,1 S,S,L
REWIND_Y2 0,1,_ -> CMP_LEX 0,1,_ S,S,R
REWIND_Y2 0,_,0 -> REWIND_Y2 0,_,0 S,S,L
REWIND_Y2 0,_,1 -> REWIND_Y2 0,_,1 S,S,L
REWIND_Y2 0,_,_ -> CMP_LEX 0,_,_ S,S,R
REWIND_Y2 0,|,0 -> REWIND_Y2 0,|,0 S,S,L
REWIND_Y2 0,|,1 -> REWIND_Y2 0,|,1 S,S,L
REWIND_Y2 0,|,_ -> CMP_LEX 0,|,_ S,S,R
REWIND_Y2 1,#,0 -> REWIND_Y2 1,#,0 S,S,L
REWIND_Y2 1,#,1 -> REWIND_Y2 1,#,1 S,S,L
REWIND_Y2 1,#,_ -> CMP_LEX 1,#,_ S,S,R
REWIND_Y2 1,0,0 -> REWIND_Y2 1,0,0 S,S,L
REWIND_Y2 1,0,1 -> REWIND_Y2 1,0,1 S,S,L
REWIND_Y2 1,0,_ -> CMP_LEX 1,0,_ S,S,R
REWIND_Y2 1,1,0 -> REWIND_Y2 1,1,0 S,S,L
REWIND_Y2 1,1,1 -> REWIND_Y2 1,1,1 S,S,L
REWIND_Y2 1,1,_ -> CMP_LEX 1,1,_ S,S,R
REWIND_Y2 1,_,0 -> REWIND_Y2 1,_,0 S,S,L
REWIND_Y2 1,_,1 -> REWIND_Y2 1,_,1 S,S,L
REWIND_Y2 1,_,_ -> CMP_LEX 1,_,_ S,S,R
REWIND_Y2 1,|,0 -> REWIND_Y2 1,|,0 S,S,L
REWIND_Y2 1,|,1 -> REWIND_Y2 1,|,1 S,S,L
REWIND_Y2 1,|,_ -> CMP_LEX 1,|,_ S,S,R
REWIND_Y2 _,#,0 -> REWIND_Y2 _,#,0 S,S,L
REWIND_Y2 _,#,1 -> REWIND_Y2 _,#,1 S,S,L
REWIND_Y2 _,#,_ -> CMP_LEX _,#,_ S,S,R
REWIND_Y2 _,0,0 -> REWIND_Y2 _,0,0 S,S,L
REWIND_Y2 _,0,1 -> REWIND_Y2 _,0,1 S,S,L
REWIND_Y2 _,0,_ -> CMP_LEX _,0,_ S,S,R
REWIND_Y2 _,1,0 -> REWIND_Y2 _,1,0 S,S,L
REWIND_Y2 _,1,1 -> REWIND_Y2 _,1,1 S,S,L
REWIND_Y2 _,1,_ -> CMP_LEX _,1,_ S,S,R
REWIND_Y2 _,_,0 -> REWIND_Y2 _,_,0 S,S,L
REWIND_Y2 _,_,1 -> REWIND_Y2 _,_,1 S,S,L
REWIND_Y2 _,_,_ -> CMP_LEX _,_,_ S,S,R
REWIND_Y2 _,|,0 -> REWIND_Y2 _,|,0 S,S,L
REWIND_Y2 _,|,1 -> REWIND_Y2 _,|,1 S,S,L
REWIND_Y2 _,|,_ -> CMP_LEX _,|,_ S,S,R
REWIND_Y2 |,#,0 -> REWIND_Y2 |,#,0 S,S,L
REWIND_Y2 |,#,1 -> REWIND_Y2 |,#,1 S,S,L
REWIND_Y2 |,#,_ -> CMP_LEX |,#,_ S,S,R
REWIND_Y2 |,0,0 -> REWIND_Y2 |,0,0 S,S,L
REWIND_Y2 |,0,1 -> REWIND_Y2 |,0,1 S,S,L
REWIND_Y2 |,0,_ -> CMP_LEX |,0,_ S,S,R
REWIND_Y2 |,1,0 -> REWIND_Y2 |,1,0 S,S,L
REWIND_Y2 |,1,1 -> REWIND_Y2 |,1,1 S,S,L
REWIND_Y2 |,1,_ -> CMP_LEX |,1,_ S,S,R
REWIND_Y2 |,_,0 -> REWIND_Y2 |,_,0 S,S,L
REWIND_Y2 |,_,1 -> REWIND_Y2 |,_,1 S,S,L
REWIND_Y2 |,_,_ -> CMP_LEX |,_,_ S,S,R
REWIND_Y2 |,|,0 -> REWIND_Y2 |,|,0 S,S,L
REWIND_Y2 |,|,1 -> REWIND_Y2 |,|,1 S,S,L
REWIND_Y2 |,|,_ -> CMP_LEX |,|,_ S,S,R
REWIND_Y2_PRE #,#,_ -> REWIND_Y2 #,#,_ S,S,L
REWIND_Y2_PRE #,0,_ -> REWIND_Y2 #,0,_ S,S,L
REWIND_Y2_PRE #,1,_ -> REWIND_Y2 #,1,_ S,S,L
REWIND_Y2_PRE #,_,_ -> REWIND_Y2 #,_,_ S,S,L
REWIND_Y2_PRE #,|,_ -> REWIND_Y2 #,|,_ S,S,L
REWIND_Y2_PRE 0,#,_ -> REWIND_Y2 0,#,_ S,S,L
REWIND_Y2_PRE 0,0,_ -> REWIND_Y2 0,0,_ S,S,L
REWIND_Y2_PRE 0,1,_ -> REWIND_Y2 0,1,_ S,S,L
REWIND_Y2_PRE 0,_,_ -> REWIND_Y2 0,_,_ S,S,L
REWIND_Y2_PRE 0,|,_ -> REWIND_Y2 0,|,_ S,S,L
REWIND_Y2_PRE 1,#,_ -> REWIND_Y2 1,#,_ S,S,L
REWIND_Y2_PRE 1,0,_ -> REWIND_Y2 1,0,_ S,S,L
REWIND_Y2_PRE 1,1,_ -> REWIND_Y2 1,1,_ S,S,L
REWIND_Y2_PRE 1,_,_ -> REWIND_Y2 1,_,_ S,S,L
REWIND_Y2_PRE 1,|,_ -> REWIND_Y2 1,|,_ S,S,L
REWIND_Y2_PRE _,#,_ -> REWIND_Y2 _,#,_ S,S,L
REWIND_Y2_PRE _,0,_ -> REWIND_Y2 _,0,_ S,S,L
REWIND_Y2_PRE _,1,_ -> REWIND_Y2 _,1,_ S,S,L
REWIND_Y2_PRE _,_,_ -> REWIND_Y2 _,_,_ S,S,L
REWIND_Y2_PRE _,|,_ -> REWIND_Y2 _,|,_ S,S,L
REWIND_Y2_PRE |,#,_ -> REWIND_Y2 |,#,_ S,S,L
REWIND_Y2_PRE |,0,_ -> REWIND_Y2 |,0,_ S,S,L
REWIND_Y2_PRE |,1,_ -> REWIND_Y2 |,1,_ S,S,L
REWIND_Y2_PRE |,_,_ -> REWIND_Y2 |,_,_ S,S,L
REWIND_Y2_PRE |,|,_ -> REWIND_Y2 |,|,_ S,S,L
REWIND_Y_PRE #,#,_ -> REWIND_Y #,#,_ S,S,L
REWIND_Y_PRE #,0,_ -> REWIND_Y #,0,_ S,S,L
REWIND_Y_PRE #,1,_ -> REWIND_Y #,1,_ S,S,L
REWIND_Y_PRE #,_,_ -> REWIND_Y #,_,_ S,S,L
REWIND_Y_PRE #,|,_ -> REWIND_Y #,|,_ S,S,L
REWIND_Y_PRE 0,#,_ -> REWIND_Y 0,#,_ S,S,L
REWIND_Y_PRE 0,0,_ -> REWIND_Y 0,0,_ S,S,L
REWIND_Y_PRE 0,1,_ -> REWIND_Y 0,1,_ S,S,L
REWIND_Y_PRE 0,_,_ -> REWIND_Y 0,_,_ S,S,L
REWIND_Y_PRE 0,|,_ -> REWIND_Y 0,|,_ S,S,L
REWIND_Y_PRE 1,#,_ -> REWIND_Y 1,#,_ S,S,L
REWIND_Y_PRE 1,0,_ -> REWIND_Y 1,0,_ S,S,L
REWIND_Y_PRE 1,1,_ -> REWIND_Y 1,1,_ S,S,L
REWIND_Y_PRE 1,_,_ -> REWIND_Y 1,_,_ S,S,L
REWIND_Y_PRE 1,|,_ -> REWIND_Y 1,|,_ S,S,L
REWIND_Y_PRE _,#,_ -> REWIND_Y _,#,_ S,S,L
REWIND_Y_PRE _,0,_ -> REWIND_Y _,0,_ S,S,L
REWIND_Y_PRE _,1,_ -> REWIND_Y _,1,_ S,S,L
REWIND_Y_PRE _,_,_ -> REWIND_Y _,_,_ S,S,L
REWIND_Y_PRE _,|,_ -> REWIND_Y _,|,_ S,S,L
REWIND_Y_PRE |,#,_ -> REWIND_Y |,#,_ S,S,L
REWIND_Y_PRE |,0,_ -> REWIND_Y |,0,_ S,S,L
REWIND_Y_PRE |,1,_ -> REWIND_Y |,1,_ S,S,L
REWIND_Y_PRE |,_,_ -> REWIND_Y |,_,_ S,S,L
REWIND_Y_PRE |,|,_ -> REWIND_Y |,|,_ S,S,L
